# vim ft=yaml
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.5
  - 3.6

env:
  global:
    # to allow AWS S3 to work
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar

install:
  - pip install -e .

script:
  - py.test -v awsbatcher
